name: Tests
on: [push]

jobs:
  pre-build-container:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Prebuild Image
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          docker build -t hamelsmu/kubeflow-triage -f prebuild.Dockerfile .
          docker push hamelsmu/kubeflow-triage
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
